export {
  MANAGER_SUPPORT_NAME,
  addManagerSupportMessage,
  addPlatformSupportMessage,
  createSupportTicket,
  getAdminSupportTicketDetail,
  getAdminSupportTicketSummary,
  getSalonSupportTicketDetail,
  getSalonSupportTicketSummary,
  listActiveSalonManagerUserIds,
  listAdminSupportTickets,
  listSalonSupportTickets,
  markSupportTicketReadByManager,
  markSupportTicketReadByPlatform,
  resolveSupportTicket,
} from './internal/support-ticket-queries'

export type {
  AdminSupportMessage,
  AdminSupportTicket,
  AdminSupportTicketDetail,
  AdminSupportTicketListInput,
  AdminSupportTicketListItem,
  ManagerSupportMessage,
  ManagerSupportTicket,
  ManagerSupportTicketDetail,
  ManagerSupportTicketListItem,
  ResolveSupportTicketResult,
  SupportMessagePreview,
  SupportTicketPage,
  SupportTicketPagination,
  SupportTicketReadResult,
  TicketMutationResult,
} from './internal/support-ticket-queries'
